### ISSUE TITLE
Implement Figma Design

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#17]
After creating a mockup and chose a final design, implement the design into the frontend.

**Tasks:**

- [x] Create css from Figma or recreate deign with bootstrap

- [x] Implement design and check it out on the web

- [x] Check for errors
