### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#19]
Start the ground structure of the LaTeX documentation. 

**Tasks:**

- [ ] Create a table of contents
- [ ] Create Headlines
- [ ] Create a list of pictures
- [ ] Create a list of tables
- [x] Create an index
