### ISSUE TITLE
Create a Server for hosting the Website

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#23]
Establish a reliable and secure server environment for hosting our website. This involves selecting configuring the server, setting up domain name system (DNS) records, ensuring security protocols are in place, and setting up a deployment process. For testing and development reasons we will use an actual miniserver with ubuntu stationed at home. To reach the server a virtual machine from Hetzner will be used to route traffic through a tunnel to the server.

**Tasks:**

- [x] Install Linux (Ubuntu) on a server 

- [x] Install Apache & MySQL

- [x] Setup DNS

- [x] Setup Apache on both servers (proxy pass, ...)

- [x] Document configuration
