### ISSUE TITLE
Get informations about sending mass e-mails

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#24]
This issue focuses on researching and documenting the best practices, tools, and regulations for sending mass emails. The goal is to find an efficient and reliable method for reaching a large audience while not getting listed on any blacklists.

**Tasks:**

- [x] Investigate various mass email service providers and compare their features, pricing, and deliverability rates

- [x] Understand and document the legal requirements for sending mass emails

- [x] Document any important information to accomplish sending mass e-mails without getting listed
