### ISSUE TITLE
Implement mass-mail functionality

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#41]
Implement a mass-mail functionality within our application. This feature will enable us to send emails to a large number of recipients efficiently and effectively. It should be capable of handling bulk email operations without compromising the performance of the system and ensure that emails are delivered in a timely manner.

**Tasks:**

- [x] Ensure the functionality adheres to email sending regulations and best practices (GDPR, CAN-SPAM Act)
- [x] Implement a queue-based system to handle bulk email sending without overloading the server
- [x] The system should efficiently handle large volumes of emails
- [x] Ensure that you do not end up on a spam list
