### ISSUE TITLE
Create a dashboard component

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#49]
This component should display an overview of the application's main features and provide quick access to different sections.

**Tasks:**

- [x] Create a new Angular component
- [x] The component should be accessible via a route /dashboard
- [x] Include placeholders for future features
- [x] Style the component to match the application's design theme.
