### ISSUE TITLE
Profile / Profile Settings

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#50]
Add a profile page for the logged in user

**Tasks:**

- [x] Add a ProfileSettings Component
- [x] Add Mail-Settings
- [x] Add OpenAi-Key Settings
- [x] Add other Key Settings
