### ISSUE TITLE
Implement Spring Security V2

### ISSUE THREAD

**Issue by Alin0u** [Alin0u/KI_Newsletter#8]
To ensure that our backend services are secure and accessible only to authorized users: integrate Spring Security. 

**Tasks:**

- [x] Implement authentication services (In-memory, JWT, OAuth2, etc.).

- [x] Add authorization policies for different endpoints.

- [x] Test all security features rigorously.
